apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: cluster-admin-tasky  # Name of the service account
    namespace: tasky  # Namespace of the service account
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Built-in role that grants full admin access
  apiGroup: rbac.authorization.k8s.io
