apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.5.2
      chart: alloy
      helm:
        valueFiles:
          - $values/values/grafana-overrides.yaml
  project: default